### ISSUE TITLE
Incredibly slow

### ISSUE THREAD

**Issue by russellbrown** [kernow/shortcode#2]
I really love the idea of this gem and it worked great when I tried it out initially, but when I invoke `Shortcode.process(input)` on anything more than a few paragraphs of text it takes ages to process.

For example, 20 paragraphs of text took several seconds, even with Lorem ipsum text that contained no shortcodes.

Since I planned to process a textarea's content every time its value changed, this would have been prohibitively slow. I'm not sure if it's due to Shortcode or its Parslet dependency, but I'm just wondering if this is expected behaviour for input text of that length?

**Comment by jheth** [comment]
I just ran into this issue as well. It's fast for small inputs but takes 20-30 seconds for larger pages of content.  +1

**Comment by adisos** [comment]
My workaround:
```ruby
def do_shortcodes
  @doc.css('*:contains("[caption")', '*:contains("[recommend")').each do |element|
    formatted_html = Shortcode.process element.inner_html
    element.inner_html = formatted_html
  end
end
```

Before it took 25 secs, now only 2-3 secs.
