### ISSUE TITLE
Cannot render Rails partial from shortcode template

### ISSUE THREAD

**Issue by sevenseacat** [kernow/shortcode#23]
Calling `render` in a template calls the method defined in `Shortcode::Tag` instead of the one defined by ActionView.

**Comment by kernow** [comment]
Supporting the `render` method requires implementing a `view_renderer` method that returns an `ActionView::Renderer` object so it's not a trivial matter to get this working. It would require a lot of rails specific code within the gem so it's not something I'll be implementing myself. If you find a way to implement `render` support in a simple way I'd be happy to accept a pull request for the feature.

I have started work on a `Shortcode::TemplateBinding` that is passed as the binding to templates, this class implements a clean interface so there will be no method name conflicts with rails helpers. I'll be pushing this code in the next couple of days.

**Comment by kernow** [comment]
I forgot to mention after the release including `Shortcode::TemplateBinding` you should be able to implement your own `render` method using a [custom helper](https://github.com/kernow/shortcode#custom-helpers)
