### ISSUE TITLE
Make Rails' URL helpers available by default

### ISSUE THREAD

**Issue by mtarnovan** [kernow/shortcode#24]
I imagine most templates will use path helpers, would it now be useful to include `Rails.application.routes.url_helpers` by default? Thanks.

**Comment by richpeck** [comment]
Has this been implemented? Having some difficulty with it

**Comment by bcackerman** [comment]
How do you include URL Helpers now?

**Comment by kernow** [comment]
@bcackerman you would need to include helpers you need in a presenter the same way you would in any ruby class, this is nothing specific to the Shortcode gem.
