### ISSUE TITLE
Option to have a shortcode stripped version

### ISSUE THREAD

**Issue by lokenmakwana** [kernow/shortcode#25]
There should be option to have text without any shortcode in it. Wordpress has function for that.
http://codex.wordpress.org/Function_Reference/strip_shortcodes

**Comment by kernow** [comment]
I assume this would be for things like excerpts of content when the shortcode content is not needed. I'll add it to the next release.

**Comment by sophiedeziel** [comment]
I was working on it today and I'm almost done. Buuuuuuuuuuuut, I just came out with that problem:

How do we recognize the content that should be completely stripped (like a photo gallery) and content that should stay (like the "[bold]This is bold text and is an important part of the sentence[/bold] and this part does not make sense without the bold part") ?

I have a solution: by default, everything is stripped. If something should not be (like bold text or images) we could have the possibility to provide a "stripped" template that could be rendered (with a naming convention). That way, people can chose to strip the entire shortcode, keep only the content or one attribute to render or render everything the same way.

Another solution would be to add some config options to chose the default behavior and some exceptions. It can be used with the "stripped templates" and become very powerful together.

**Comment by kernow** [comment]
I would expect this feature to simply strip the shortcode tags out and nothing more. So `Some [bold]bold text[/bold].` would become `Some bold text.`. Essentially anything inside square brackets is removed including the square brackets with no regard for start or end tags.
