### ISSUE TITLE
Removing whitspace after shortcode

### ISSUE THREAD

**Issue by alesrosina** [kernow/shortcode#26]
When shortcode does it's magic replacing with a template, it ignores whitespace after tag.

Example:
I have defined block tag [link] with this template:
    `<%= link_to(@content, "#{@attributes[:to]}") %>`
It replaces text correctly with a href html tag, but in removes endig whitespace, eg:
    `This is [link to:"/test"]test[/link] link.`
transforms to:
    `This is <a href="/test">test</a>link.`
Note the removal of whitespace between words test and link.

If I have a case like this:
   ` This is [link to:"/test"]test[/link]. New sentence is ok now.`
transforms correctly to:
    `This is <a href="/test">test</a>. New sentence is ok now.`
Note the whitespace after `.` is correctly shown.

Is it a feature? :)

**Comment by kernow** [comment]
Looks like this is a bug, I'll see if I can make some time to fix it this week.

**Comment by alesrosina** [comment]
Perfect, thanks for your fast response!

**Comment by kernow** [comment]
@alesrosina could you try the latest master branch and check that it fixes your issue. I'll release an updated version if it resolved the problem.

**Comment by alesrosina** [comment]
@kernow it works like a charm.

Thanks for your fast response!

**Comment by kernow** [comment]
No problem, I've pushed version 1.0.2 with the fix.
