### ISSUE TITLE
block_tags order breaks functioning

### ISSUE THREAD

**Issue by Epigene** [kernow/shortcode#35]
This is really strange. The order of template symbols sharing the same first letter can make or break their function. If the longer ones are placed first, it works, otherwise the latter placed, longer symbol templates are not found.

Say I define two templates
```ruby
config.block_tags = [:xx, :xx2]
```

And their contents are a trivial
```slim
strong
  = raw @content
```

In console
```
Shortcode.process("[xx]bold[/xx]") #=> "<strong>bold</strong>"
Shortcode.process("[xx2]bold[/xx2]") #=> "[xx2]bold[/xx2]"
```

The second output is the bug.

**Comment by kernow** [comment]
Hi, could you post a full example where this is an issue please. Or even better create a failing test on a fork of the code so that I can take a look. Thanks

**Comment by Epigene** [comment]
Made a test app reproducing the issue
https://github.com/Epigene/shortcode_test

Setup:
```
git clone
bundle
rake db:create (uses PG)
```

Then run the two specs with
```
rspec
```

The first test passes, the second fails.

**Comment by kernow** [comment]
I've had a look into this and I'm not sure if it's a bug in Shortcode or the Parslet gem. It appears as though the tag nam `xx2` is being matched but whole tag `[xx2]` is not matching for some reason. I've asked for clarification on how parslet should work.

For now a work around that appears to work is to define xx2 before xx in the array.

**Comment by kernow** [comment]
Version 1.1.1 released that should fix this issue

**Comment by Epigene** [comment]
Thanks, I appreciate the quick fix.
