### ISSUE TITLE
Processing only specified tags

### ISSUE THREAD

**Issue by atothewest** [kernow/shortcode#36]
Hi, apologies if this is asked/explained elsewhere. Suppose I have multiple tags registered and I only want to process a piece of content for one of these tags, how would I go about that? 

So, for example, I have: 

config.self_closing_tags = [:foo, :bar] 

And then a string: 

"I want to process [foo] but not [bar]".

**Comment by kernow** [comment]
Hi, there is no support for this behaviour built in. You would either have to only pass in the section of the string containing the tags you want to process or remove :bar from the registered tags.

Regarding the second approach you could do this on the fly by calling the setup block multiple times and redefining the registered tags, you would need to restore the registered tags to their original state after parsing the string.

**Comment by atothewest** [comment]
Ok cool, thanks. Will give that a shot.
