### ISSUE TITLE
A copy of *ProductImagePresenter* has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by chr1s1** [kernow/shortcode#40]
Hi, 

I am currently facing a really weird problem and I hope one of you is able to help me solving it. 

I have 2 Presenter Classes inside classes/. Every time I change the content which includes the shortcodes I get a error message like this:

`A copy of ProductImagePresenter has been removed from the module tree but is still active!`

If I restart the rails server it is working, but this is not the solution. 

Files: 
/app/classes/product_image_presenter.rb
/app/classes/product_name_presenter.rb
/app/views/shortcode_templates/product_image.html.erb
/app/views/shortcode_templates/product_name.html.erb

Example Content:
`<td>[product_image id="4482698"]<br />[product_name id="4482698"]</td>`

**Comment by kernow** [comment]
Hi, I assume you are using Shortcode within a rails app. This error happens because of the way rails reloads classes in development mode, you will need yo reload your rails app each time you make a change to a presenter.

**Comment by chr1s1** [comment]
The point is, I am not changing the presenter. I am changing the content.E.g.

From:
`<td>[product_image id="4482698"]<br />[product_name id="4482698"]</td>`

To: 
`<td>[product_image id="1"]<br />[product_name id="1"]</td>`

**Comment by kernow** [comment]
You haven't provided enough information to help. I would suspect the issue is somewhere in the way you have coded your application but it's impossible to say without seeing all of the code relating to how you are invoking the gem, the presenters and templates.

**Comment by chr1s1** [comment]
Do you put you presenters in the same folder? Maybe thats the problem?

**Comment by kernow** [comment]
No, I mean that you haven't posted your code so that people can see it an try to help. It's impossible to help without seeing your code.

**Comment by chr1s1** [comment]
That's easy to solve. I have the feeling the reason is the Modul called Helper.
Path `/app/classes/product_image_presenter.rb`
```
class ProductImagePresenter
  include HelperModule

  def self.for
    :product_image
  end

  def initialize(attributes, content, additional_attributes)
    @content = content
    @attributes = attributes
    @id = attributes[:id]
  end

  def content
    @content
  end

  def attributes
    {
        id: @id,
        name: name
    }
  end

  private

  def name
    product = Product.where("id = ?", @attributes[:id].to_i).first
    product.name unless product.nil?
  end
end
```

Controller:
Path `/app/controllers/compare_controller.rb`
```
class CompareController < ApplicationController
  def index
    # variable to test if the shortcodes work
    @description = '[product_image id="4482698"]' 
  end
end
```

View: 
```
<h1>Compare#index</h1>
<p>Find me in app/views/compare/index.html.erb</p>
<p><%= shortcode_with_html @description %></p>
```

Shortcode Template (Just to test it):
`<%= @attributes[:name] %>`

Compare Helper:
Path: `app/helpers/compare_helper.rb`
```
module CompareHelper
  def shortcode(c)
    Shortcode.process(c)
  end

  def shortcode_with_html(c)
    raw shortcode(c)
  end
end
```

Helper Module
Path: `app/classes/helper_module.rb`

```
module HelperModule
  def image_host
    if Rails.env.production?
      "..."
    else
      "localhost:3000"
    end
  end
end
```
