### ISSUE TITLE
Forgetting to open/close attribute value breaks the whole system that uses this gem

### ISSUE THREAD

**Issue by rreimche** [kernow/shortcode#42]
Hi!

If someone forgets to close the value of an attribute, I get an exception from the parsing gem.

For example, [myshortcode myattribute="myvalue ]mycontent[/myshortcode]
or [myshortcode myattribute=myvalue" ]mycontent[/myshortcode]
or [myshortcode myattribute=myvalue ]mycontent[/myshortcode]

gives 

Extra input after last repetition at line 8 char 1. 

Full trace is [here](http://pastebin.com/gEg7x6Kh).

This is extremely not fool-proof. As a solution I would propose just skipping processing or also giving error message, but not complete system crash ,)

**Comment by kernow** [comment]
Hi,

The gem should probably catch these errors and re-raise it's own error. Failing silently would not be desirable as it would not give users the opportunity to do something different in this situation.

Your solution would be the same should the error be re-raised or with the gem as it currently is, you can catch the exception and return the original string. If an error is re-raised in the future you would simply need to change the error that you are catching.
