### ISSUE TITLE
Per instance configuration

### ISSUE THREAD

**Issue by leonardoalifraco** [kernow/shortcode#43]
Hi @kernow,

Quick question: Is there any way to have different setups per processor / parser instance?
I can see that currently it is loading the configuration directly from the Shortcode class.

For example:

```
  rule(:block_tag)        { match_any_of Shortcode.configuration.block_tags }
  rule(:self_closing_tag) { match_any_of Shortcode.configuration.self_closing_tags }
```

**Comment by kernow** [comment]
Unfortunately not without rewriting the code to invoke an instance of `Shortcode` rather than using a singleton pattern for the main object.

Do you want to have the same shortcode tags handled differently within the same app?

**Comment by leonardoalifraco** [comment]
Yes. That's what i need right now. Would you be open to launch a new release if I manage to keep the singleton functionality as default but be able to inject a configuration instance in the classes that use it?

**Comment by kernow** [comment]
Should be resolved by https://github.com/kernow/shortcode/pull/45
