### ISSUE TITLE
Allow loading templates from config AND files

### ISSUE THREAD

**Issue by toddnestor** [kernow/shortcode#47]
I believe when loading templates it should first check the config and if it doesn't find a template there it should check the file structure.

I can put in a PR for this.

**Comment by kernow** [comment]
Maybe a config option for the load order priority could be added but it maybe overkill.

**Comment by toddnestor** [comment]
That'd be an easy option to have, so might as well :) Let the gem users decide how they want it to happen.

**Comment by toddnestor** [comment]
This should be done before #46 so I'll do this one first.
