### ISSUE TITLE
Deprecate singleton usage

### ISSUE THREAD

**Issue by kernow** [kernow/shortcode#49]
Now that instances of `Shortcode` can be created singleton usage should be deprecated.

@toddnestor are you happy all of the cases that need warnings have been covered by this commit https://github.com/kernow/shortcode/commit/8f539c8110d25d50e331c57fa4dca24a274dd16c

**Comment by toddnestor** [comment]
Yeah, it looks good to me. Thanks for doing that and for getting a new release out! I can update the CMS at my company now!

**Comment by krisdigital** [comment]
I am getting a [DEPRECATION] on each Rails start, I think it is thrown by Shortcode itself:
https://github.com/kernow/shortcode/blob/master/lib/shortcode.rb#L68

**Comment by toddnestor** [comment]
@krisdigital yes it will show a deprecation warning if you have upgraded to the latest version.  You could force the previous version in your Gemfile if you don't want to see the deprecation warnings.

The deprecation warnings are there to let you know the singleton usage of the Shortcode gem is being deprecated in 2.0 and so if you upgrade to that version without changing your code it will stop working for you.

**Comment by kernow** [comment]
@krisdigital @toddnestor I'm going to try and work on the 2.0 release over the next week or 2. If you follow the guide in the readme on usage (by creating an instance of `Shortcode`) then you should not have any issues upgrading to the 2.0 release.

**Comment by krisdigital** [comment]
@toddnestor ok, but why do I get warnings if I do not use the singleton anymore? warning everybody even if he has already updated seems a bit overkill to me..

**Comment by stevehanson** [comment]
I feel like there should be some way to turn off the deprecation message if my code isn't actually using the singleton. I just searched through my codebase trying to find where I was doing so just to realize the deprecation message shows regardless of any usage.

**Comment by kernow** [comment]
I've released 2.0.0.pre today which completely removes the singleton code so you won't get any deprecation warnings. If you could test it out and check it is working for you that would be great.

**Comment by stevehanson** [comment]
@kernow just pulled it down, and it is working for me, and I'm no longer getting the deprecation warning 👍  Would you consider this version safe for production or should I wait for 2.0.0 to come along?

**Comment by kernow** [comment]
@stevehanson glad it's working for you. Re: production ready, it depends on you're attitude to risk, I'm not aware of any issues and in terms of code changes you can see that the main 2.0 change is removing the singleton support. I don't see why you would experience any problem but I wanted to have a prerelease period incase anyone has issues upgrading.

**Comment by stevehanson** [comment]
Thanks, @kernow! I'll probably upgrade in the next couple weeks. 👍
