### ISSUE TITLE
Can't get it to process template

### ISSUE THREAD

**Issue by sbarre5** [kernow/shortcode#53]
I can't get the shortcode to process the template. It's just spitting out exactly what I have in my view. Example:

`<%= Shortcode.process("[quote author='Homer Simpson']Hello World[/quote]") %>`
is simply being written as: `[quote author='Homer Simpson']Hello World[/quote]` to my body.

Here is how i've set it up in my application:

**shortcode.rb initializer**
```ruby
require "shortcode"
shortcode = Shortcode.new
shortcode.setup do |config|
  config.template_parser = :erb # :erb, :haml, :slim supported, :erb is default
  config.template_path = "app/views/shortcode_templates"
  config.templates = { quote: 'quote' }
  config.check_config_templates_first = true
  config.block_tags = [:quote]
  config.self_closing_tags = [:youtube]
  config.attribute_quote_type = '"'
  config.use_attribute_quotes = true
end
```

**pages_controller.rb**
`require "shortcode"`

I have a folder views/shortcode_templates with a file called quote.html.erb

Any idea what I am doing wrong?

**Comment by kernow** [comment]
@sbarre5 you are configuring an instance of shortcode in the initializer but then you are calling `Shortcode` in the view which is a singleton. You can't mix these two. You will need to call `process` on the instance you create in the initializer for it to work correctly.

**Comment by sbarre5** [comment]
@kernow - thanks for your answer. I apologize as I am very new at RoR and just trying to get my feet wet so I'm sure these are simple instructions.

Without changing anything in my shortcode.rb initializer, I added this to my view:

`<% testShortcode = Shortcode.new %>
<%= testShortcode.process("[quote author='Homer Simpson']Hello World[/quote]") %>`

I still can't get it to render. I know it's initializing properly because I get the deprecation warning. 

Note: I did try to call `<%= shortcode.process("[quote author='Homer Simpson']Hello World[/quote]") %>` in my view but received an error: undefined local variable or method `shortcode'. 

Thanks for your help.

**Comment by sbarre5** [comment]
@kernow - any ideas? I'm trying to get this to work for a customer and they're on a pretty short timeline. I'd love to use this GEM if I can get it working.

Thank you!

Saundra
