### ISSUE TITLE
Wordpress syntax compatibility, i.e. parse [example /]

### ISSUE THREAD

**Issue by fabn** [kernow/shortcode#54]
I'm trying to use this gem to process some shortcodes returned by a wordpress installation, however in wordpress a self closing tag may have a trailing slash (`[example /]` is the same thing as `[example]`).

Is there any way to have them parsed?

Current release seems to not support this syntax.

Thanks.

**Comment by kernow** [comment]
@fabn I don't believe it currently supports that style of tag, I'm happy to accept pull requests that add support.

**Comment by fabn** [comment]
Hi @kernow, I need this feature because wordpress sometimes returns the slash. If you give me some hints on how to implement the feature I'll try to sketch some code and a PR.

Thanks.
