### ISSUE TITLE
Image tag not being fingerprinted

### ISSUE THREAD

**Issue by alexbrinkman** [kernow/shortcode#55]
Hello!
I have an <%= image_tag "badge" %> in one of my shortcode templates.  The code compiles fine, but the resulting image doesn't get fingerprinted, and therefore shows as a broken image.  The source of the image is "/images/badge.png", which doesn't work, whereas outside of a shortcode template it would be "/assets/badge-sha-fingerprint.png", which does work.   What am I missing?

Thanks!

**Comment by kernow** [comment]
Hi @alexbrinkman you would be best to post this on stackoverflow or similar as it looks likely it's a rails issue rather than a shortcode issue.

**Comment by leoncustodio** [comment]
@alexbrinkman Did you get any luck here?

**Comment by alexbrinkman** [comment]
Ok, sounds good.  I'm not working on that project any longer, so it will be hard to test.  I think it's fine to just close this out.
